#!/bin/bash -e

options=()
target=""
remote_cmd=()
user=""
path=""

for arg in "$@"; do
    if [[ -z "$target" && "$arg" == *:* ]]; then
        target="$arg"
    elif [[ -z "$target" ]]; then
        options+=("$arg")
    else
        remote_cmd+=("$arg")
    fi
done

if [[ -z "$target" ]]; then
    echo "Usage: $0 [ssh options] [user@]host:/path [command]" >&2
    exit 1
fi

usertest="${target%%:*}"
path="${target#*:}"

if [[ "$usertest" == *"@"* ]]; then
    user="${usertest%%@*}"
    host="${usertest#*@}"
else
    host="$usertest"
fi

[[ -n "$user" ]] && remote="${user}@${host}" || remote="${host}"

path_escaped=$(printf "%q" "$path")

if [[ ${#remote_cmd[@]} -gt 0 ]]; then
    cmd=$(printf "%q " "${remote_cmd[@]}")
    exec ssh "${options[@]}" "${remote}" "cd $path_escaped && exec $cmd"
else
    exec ssh -t "${options[@]}" "${remote}" "cd $path_escaped; exec \$SHELL -l"
fi

